# Generated by Django 3.0.4 on 2020-04-17 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200417_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='currenT_location',
            new_name='current_location',
        ),
    ]
